name: Talismans
version: ${projectVersion}
main: com.willfp.talismans.TalismansPlugin
api-version: 1.16
authors: [ Auxilor ]
website: willfp.com
load: STARTUP
depend:
  - eco
softdepend:
  - EcoSkills
  - AureliumSkills
  - Vault
  - mcMMO
  - Jobs
  - EcoArmor
  - TMMobcoins
  - EcoBosses
commands:
  talismans:
    description: Parent command.
    permission: talismans.command.talismans
    aliases:
      - talisman
      - talis
      - talismen
      - tal

permissions:
  talismans.*:
    description: All talismans permissions
    default: op
    children:
      talismans.command.talismans: true
      talismans.command.give: true
      talismans.command.bag: true
      talismans.command.reload: true
      talismans.fromtable.*: true

  talismans.command.reload:
    description: Allows reloading the config
    default: op
  talismans.command.give:
    description: Allows the use of /talismans give.
    default: op
  talismans.command.bag:
    description: Allows the use of /talismans bag.
    default: true
  talismans.command.talismans:
    description: Allows the use of /talismans
    default: true
  talismans.fromtable.*:
    description: Allows crafting all talismans
    default: true